const canvas=document.getElementById("gameCanvas");const ctx=canvas.getContext("2d");
const menuScreen=document.getElementById("menuScreen"),gameScreen=document.getElementById("gameScreen"),playButton=document.getElementById("playButton");
const difficultyButtons=document.querySelectorAll(".difficulty"),menuHighScore=document.getElementById("menuHighScore"),menuBestScore=document.getElementById("menuBestScore"),menuCoins=document.getElementById("menuCoins"),menuMode=document.getElementById("menuMode");
const scoreText=document.getElementById("score"),livesText=document.getElementById("lives"),coinsText=document.getElementById("coins"),highScoreText=document.getElementById("highScore"),startButton=document.getElementById("startButton");
const leftButton=document.getElementById("leftButton"),rightButton=document.getElementById("rightButton"),runMode=document.getElementById("runMode"),lifeIcons=document.getElementById("lifeIcons");
let player,enemies=[],coins=[],score=0,lives=3,coinCount=0,gameRunning=false,paused=false,animationId,roadOffset=0,hitCooldown=0,crashEffect=0,selectedDifficulty="easy";
let highScore=Number(localStorage.getItem("trafficDodgeHighScore"))||0;
let totalCoins=Number(localStorage.getItem("trafficDodgeCoins"))||0;
function syncMenu(){menuHighScore.textContent=highScore;menuBestScore.textContent=highScore;menuCoins.textContent=totalCoins;menuMode.textContent=selectedDifficulty.toUpperCase()}
function syncLives(){livesText.textContent=lives;[...lifeIcons.children].forEach((x,i)=>x.classList.toggle("off",i>=lives))}
syncMenu();highScoreText.textContent=highScore;
const difficultySettings={easy:{enemySpeed:3.5,spawnTime:1200,coinTime:1000},normal:{enemySpeed:4.5,spawnTime:1000,coinTime:1200},hard:{enemySpeed:6,spawnTime:750,coinTime:1400}};
const road={x:50,width:300};let audioContext=null;
function initAudio(){if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)()}
function playSound(frequency,duration,type="sine",volume=.08){if(!audioContext)return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=frequency;g.gain.value=volume;o.connect(g);g.connect(audioContext.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);o.stop(audioContext.currentTime+duration)}
difficultyButtons.forEach(button=>button.addEventListener("click",()=>{difficultyButtons.forEach(x=>x.classList.remove("active"));button.classList.add("active");selectedDifficulty=button.dataset.level;syncMenu()}));
function resetGame(){player={x:175,y:500,width:50,height:80,speed:20};enemies=[];coins=[];score=0;lives=3;coinCount=0;roadOffset=0;hitCooldown=0;crashEffect=0;paused=false;gameRunning=true;scoreText.textContent=score;coinsText.textContent=coinCount;highScoreText.textContent=highScore;syncLives();runMode.textContent=selectedDifficulty.toUpperCase()}
function drawRoad(){ctx.fillStyle="#174d25";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#555";ctx.fillRect(road.x,0,road.width,canvas.height);ctx.fillStyle="#fff";ctx.fillRect(road.x,0,5,canvas.height);ctx.fillRect(road.x+road.width-5,0,5,canvas.height);roadOffset+=8;if(roadOffset>=60)roadOffset=0;ctx.strokeStyle="#fff";ctx.lineWidth=5;ctx.setLineDash([30,30]);ctx.lineDashOffset=roadOffset;ctx.beginPath();ctx.moveTo(150,0);ctx.lineTo(150,canvas.height);ctx.stroke();ctx.beginPath();ctx.moveTo(250,0);ctx.lineTo(250,canvas.height);ctx.stroke();ctx.setLineDash([]);ctx.lineDashOffset=0;drawTrees()}
function drawTrees(){[80,320].forEach(x=>{for(let y=-100;y<canvas.height+100;y+=130){const treeY=(y+roadOffset*2)%700-100;ctx.fillStyle="#795548";ctx.fillRect(x-5,treeY+25,10,30);ctx.fillStyle="#2e7d32";ctx.beginPath();ctx.arc(x,treeY+20,23,0,Math.PI*2);ctx.fill()}})}
function drawPlayer(){if(hitCooldown>0&&Math.floor(hitCooldown/5)%2===0)return;ctx.fillStyle="#1976d2";ctx.fillRect(player.x,player.y,player.width,player.height);ctx.fillStyle="#1565c0";ctx.fillRect(player.x+7,player.y+8,player.width-14,48);ctx.fillStyle="#b3e5fc";ctx.fillRect(player.x+10,player.y+13,player.width-20,18);ctx.fillRect(player.x+10,player.y+35,player.width-20,15);ctx.fillStyle="#111";ctx.fillRect(player.x-5,player.y+10,8,22);ctx.fillRect(player.x+player.width-3,player.y+10,8,22);ctx.fillRect(player.x-5,player.y+50,8,22);ctx.fillRect(player.x+player.width-3,player.y+50,8,22);ctx.fillStyle="#fff59d";ctx.fillRect(player.x+6,player.y+2,10,6);ctx.fillRect(player.x+player.width-16,player.y+2,10,6)}
function createEnemy(){const lanes=[75,175,275],lane=lanes[Math.floor(Math.random()*lanes.length)],colors=["#e53935","#43a047","#8e24aa","#fb8c00"],settings=difficultySettings[selectedDifficulty],difficultyBoost=Math.min(score*.05,4);enemies.push({x:lane,y:-100,width:50,height:80,speed:settings.enemySpeed+Math.random()*2+difficultyBoost,color:colors[Math.floor(Math.random()*colors.length)]})}
function drawEnemies(){enemies.forEach(e=>{ctx.fillStyle=e.color;ctx.fillRect(e.x,e.y,e.width,e.height);ctx.fillStyle="#222";ctx.fillRect(e.x+7,e.y+8,e.width-14,48);ctx.fillStyle="#b3e5fc";ctx.fillRect(e.x+10,e.y+13,e.width-20,18);ctx.fillRect(e.x+10,e.y+35,e.width-20,15);ctx.fillStyle="#111";ctx.fillRect(e.x-5,e.y+10,8,22);ctx.fillRect(e.x+e.width-3,e.y+10,8,22);ctx.fillRect(e.x-5,e.y+50,8,22);ctx.fillRect(e.x+e.width-3,e.y+50,8,22)})}
function createCoin(){const lanes=[75,175,275],lane=lanes[Math.floor(Math.random()*lanes.length)];coins.push({x:lane+25,y:-30,radius:13,speed:4})}
function drawCoins(){coins.forEach(c=>{ctx.fillStyle="#ffd700";ctx.beginPath();ctx.arc(c.x,c.y,c.radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#fff176";ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#8d6e00";ctx.font="bold 16px Arial";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("$",c.x,c.y)})}
function updateEnemies(){enemies.forEach(e=>e.y+=e.speed);enemies=enemies.filter(e=>{if(e.y>canvas.height){score++;scoreText.textContent=score;return false}return true})}
function updateCoins(){coins.forEach(c=>c.y+=c.speed);coins=coins.filter(c=>c.y<canvas.height+50)}
function isColliding(a,b){return a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y}
function checkEnemyCollision(){if(hitCooldown>0)return;for(let i=0;i<enemies.length;i++){const e=enemies[i];if(isColliding(player,e)){enemies.splice(i,1);lives--;syncLives();hitCooldown=120;crashEffect=20;playSound(100,.35,"sawtooth",.15);player.x=175;if(lives<=0)endGame();return}}}
function checkCoinCollision(){for(let i=coins.length-1;i>=0;i--){const c=coins[i],box={x:c.x-c.radius,y:c.y-c.radius,width:c.radius*2,height:c.radius*2};if(isColliding(player,box)){coins.splice(i,1);coinCount++;totalCoins++;localStorage.setItem("trafficDodgeCoins",totalCoins);coinsText.textContent=coinCount;score+=5;scoreText.textContent=score;playSound(800,.12,"sine",.1)}}}
function drawCrashEffect(){if(crashEffect<=0)return;ctx.fillStyle=`rgba(255,80,0,${crashEffect/30})`;ctx.fillRect(0,0,canvas.width,canvas.height);crashEffect--}
function endGame(){gameRunning=false;paused=false;cancelAnimationFrame(animationId);if(score>highScore){highScore=score;localStorage.setItem("trafficDodgeHighScore",highScore)}highScoreText.textContent=highScore;syncMenu();ctx.fillStyle="rgba(0,0,0,.84)";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.textAlign="center";ctx.fillStyle="#fff";ctx.font="900 40px Arial";ctx.fillText("GAME OVER",canvas.width/2,220);ctx.font="700 22px Arial";ctx.fillText(`Score: ${score}`,canvas.width/2,270);ctx.fillText(`Coins: ${coinCount}`,canvas.width/2,308);ctx.fillStyle="#ffd65a";ctx.fillText(`Best: ${highScore}`,canvas.width/2,346);ctx.fillStyle="#39f59a";ctx.font="900 15px Arial";ctx.fillText("PRESS PAUSE BUTTON FOR MENU",canvas.width/2,390);startButton.textContent="↩"}
function drawPauseScreen(){ctx.fillStyle="rgba(0,0,0,.66)";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="900 42px Arial";ctx.fillText("PAUSED",canvas.width/2,canvas.height/2);ctx.font="12px Arial";ctx.fillStyle="#39f59a";ctx.fillText("TAP PAUSE TO RESUME",canvas.width/2,canvas.height/2+32)}
function gameLoop(){if(!gameRunning)return;ctx.clearRect(0,0,canvas.width,canvas.height);if(!paused){if(hitCooldown>0)hitCooldown--;drawRoad();updateEnemies();updateCoins();drawEnemies();drawCoins();drawPlayer();checkEnemyCollision();checkCoinCollision();drawCrashEffect()}else{drawRoad();drawEnemies();drawCoins();drawPlayer();drawPauseScreen()}animationId=requestAnimationFrame(gameLoop)}
function startGame(){initAudio();if(audioContext&&audioContext.state==="suspended")audioContext.resume();cancelAnimationFrame(animationId);resetGame();menuScreen.classList.add("hidden");gameScreen.classList.remove("hidden");startButton.textContent="Ⅱ";gameLoop()}
function backToMenu(){gameRunning=false;paused=false;cancelAnimationFrame(animationId);gameScreen.classList.add("hidden");menuScreen.classList.remove("hidden");syncMenu()}
function togglePause(){if(!gameRunning)return;paused=!paused;startButton.textContent=paused?"▶":"Ⅱ"}
function moveLeft(){if(!gameRunning||paused)return;player.x-=player.speed;if(player.x<road.x)player.x=road.x}
function moveRight(){if(!gameRunning||paused)return;player.x+=player.speed;if(player.x+player.width>road.x+road.width)player.x=road.x+road.width-player.width}
document.addEventListener("keydown",e=>{if(e.key==="ArrowLeft")moveLeft();if(e.key==="ArrowRight")moveRight();if(e.key===" ")togglePause()});
leftButton.addEventListener("touchstart",e=>{e.preventDefault();moveLeft()});rightButton.addEventListener("touchstart",e=>{e.preventDefault();moveRight()});leftButton.addEventListener("click",moveLeft);rightButton.addEventListener("click",moveRight);
startButton.addEventListener("click",()=>{if(!gameRunning&&startButton.textContent==="↩"){backToMenu();return}if(!gameRunning)startGame();else togglePause()});
playButton.addEventListener("click",startGame);
setInterval(()=>{if(gameRunning&&!paused)createEnemy()},1000);
setInterval(()=>{if(gameRunning&&!paused)createCoin()},1200);