const $=id=>document.getElementById(id);
const canvas=$("gameCanvas"),ctx=canvas.getContext("2d");
const menu=$("menuScreen"),game=$("gameScreen"),play=$("playButton"),pause=$("pauseButton");
const scoreEl=$("score"),livesEl=$("lives"),coinsEl=$("coins"),bestEl=$("highScore"),modeEl=$("modeText");
const menuBest=$("menuHighScore"),menuCoins=$("menuTotalCoins"),menuTotal=$("menuCoins");
const left=$("leftButton"),right=$("rightButton");
let selected="easy",running=false,paused=false,raf=0,score=0,lives=3,coins=0,high=Number(localStorage.getItem("trafficDodgeHighScore"))||0,total=Number(localStorage.getItem("trafficDodgeCoins"))||0;
let player,enemies=[],pickupCoins=[],lastEnemy=0,lastCoin=0,inv=0;
const settings={easy:{speed:3.5,enemy:1050,coin:1100},normal:{speed:4.7,enemy:850,coin:1050},hard:{speed:6.2,enemy:650,coin:950}};
const road={x:50,w:300};
function menuSync(){menuBest.textContent=high;menuCoins.textContent=total}
menuSync();bestEl.textContent=high;
document.querySelectorAll(".difficulty-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".difficulty-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");selected=b.dataset.level;modeEl.textContent=selected.toUpperCase()});
function reset(){player={x:175,y:500,w:50,h:80,speed:20};enemies=[];pickupCoins=[];score=0;lives=3;coins=0;inv=0;lastEnemy=performance.now();lastCoin=performance.now();scoreEl.textContent=0;coinsEl.textContent=0;bestEl.textContent=high;livesEl.textContent="❤️❤️❤️";modeEl.textContent=selected.toUpperCase()}
function car(x,y,w,h,color,enemy=false){ctx.fillStyle=color;ctx.fillRect(x,y,w,h);ctx.fillStyle=enemy?"#222":"#0c5b3c";ctx.fillRect(x+7,y+8,w-14,48);ctx.fillStyle="#9fd9e9";ctx.fillRect(x+10,y+13,w-20,18);ctx.fillRect(x+10,y+35,w-20,15);ctx.fillStyle="#080a0d";ctx.fillRect(x-5,y+10,8,22);ctx.fillRect(x+w-3,y+10,8,22);ctx.fillRect(x-5,y+50,8,22);ctx.fillRect(x+w-3,y+50,8,22)}
function roadDraw(){ctx.fillStyle="#0b2a1d";ctx.fillRect(0,0,400,600);ctx.fillStyle="#2b3440";ctx.fillRect(50,0,300,600);ctx.fillStyle="#dce4ea";ctx.fillRect(50,0,4,600);ctx.fillRect(346,0,4,600);ctx.setLineDash([32,28]);ctx.lineWidth=5;ctx.strokeStyle="#eef2f5";ctx.lineDashOffset=-(performance.now()/9)%60;for(const x of [150,250]){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,600);ctx.stroke()}ctx.setLineDash([])}
function spawnEnemy(){const lanes=[75,175,275];const x=lanes[Math.floor(Math.random()*3)];enemies.push({x,y:-90,w:50,h:80,s:settings[selected].speed+Math.random()*1.8,c:["#ef4253","#36a35a","#8158e8","#f39b2d"][Math.floor(Math.random()*4)]})}
function spawnCoin(){const lanes=[75,175,275];pickupCoins.push({x:lanes[Math.floor(Math.random()*3)]+25,y:-20,r:13,s:4})}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function loop(t){if(!running)return;ctx.clearRect(0,0,400,600);roadDraw();if(!paused){if(t-lastEnemy>settings[selected].enemy){spawnEnemy();lastEnemy=t}if(t-lastCoin>settings[selected].coin){spawnCoin();lastCoin=t}if(inv>0)inv--;enemies.forEach(e=>e.y+=e.s);pickupCoins.forEach(c=>c.y+=c.s);for(let i=enemies.length-1;i>=0;i--){let e=enemies[i];if(e.y>620){enemies.splice(i,1);score++;scoreEl.textContent=score}else if(inv===0&&hit(player,e)){enemies.splice(i,1);lives--;inv=90;livesEl.textContent="❤️".repeat(lives)+"🖤".repeat(3-lives);player.x=175;if(lives<=0){end();return}}}for(let i=pickupCoins.length-1;i>=0;i--){let c=pickupCoins[i],b={x:c.x-c.r,y:c.y-c.r,w:c.r*2,h:c.r*2};if(hit(player,b)){pickupCoins.splice(i,1);coins++;score+=5;coinsEl.textContent=coins;scoreEl.textContent=score;total++;localStorage.setItem("trafficDodgeCoins",total);menuCoins.textContent=total}else if(c.y>630)pickupCoins.splice(i,1)}}enemies.forEach(e=>car(e.x,e.y,e.w,e.h,e.c,true));pickupCoins.forEach(c=>{ctx.fillStyle="#ffd43b";ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,Math.PI*2);ctx.fill();ctx.fillStyle="#805d00";ctx.font="bold 15px Arial";ctx.textAlign="center";ctx.fillText("$",c.x,c.y+5)});if(inv===0||Math.floor(inv/6)%2)car(player.x,player.y,player.w,player.h,"#20dc8a");if(paused){ctx.fillStyle="#000b";ctx.fillRect(0,0,400,600);ctx.fillStyle="#38f59b";ctx.font="900 42px Arial";ctx.textAlign="center";ctx.fillText("PAUSED",200,275);ctx.font="14px Arial";ctx.fillStyle="#fff";ctx.fillText("Tap Ⅱ to resume",200,310)}raf=requestAnimationFrame(loop)}
function start(){reset();running=true;paused=false;menu.classList.add("hidden");game.classList.remove("hidden");pause.textContent="Ⅱ";raf=requestAnimationFrame(loop)}
function end(){running=false;cancelAnimationFrame(raf);if(score>high){high=score;localStorage.setItem("trafficDodgeHighScore",high)}bestEl.textContent=high;menuSync();ctx.fillStyle="#000d";ctx.fillRect(0,0,400,600);ctx.textAlign="center";ctx.fillStyle="#ff5262";ctx.font="900 40px Arial";ctx.fillText("GAME OVER",200,230);ctx.fillStyle="#fff";ctx.font="bold 20px Arial";ctx.fillText("SCORE  "+score,200,275);ctx.fillText("COINS  "+coins,200,310);ctx.fillStyle="#ffd43b";ctx.fillText("BEST  "+high,200,345);ctx.fillStyle="#39f59a";ctx.font="bold 12px Arial";ctx.fillText("PAUSE BUTTON = BACK TO MENU",200,390);pause.textContent="⌂"}
function togglePause(){if(!running)return;if(!paused){paused=true;pause.textContent="▶"}else{paused=false;pause.textContent="Ⅱ"}}
function back(){running=false;paused=false;cancelAnimationFrame(raf);game.classList.add("hidden");menu.classList.remove("hidden");menuSync();pause.textContent="Ⅱ"}
function move(dir){if(!running||paused)return;player.x+=dir*player.speed;player.x=Math.max(50,Math.min(300,player.x))}
play.onclick=start;pause.onclick=()=>{if(!running){back()}else togglePause()};left.onclick=()=>move(-1);right.onclick=()=>move(1);
document.addEventListener("keydown",e=>{if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1);if(e.code==="Space")togglePause()});
